### ISSUE TITLE
impersonating me huh, lol nice try

### ISSUE THREAD

**Issue by swagging-post** [Githubman6996/Minesraft2-blooket-hack-website#2]
don't follow your own account when you're trying to be "secret", idiot.

**Comment by Githubman6996** [comment]
That’s not me

**Comment by Githubman6996** [comment]
Wdym

**Comment by Githubman6996** [comment]
Im not impersonating anyone

**Comment by swagging-post** [comment]
Following yourself on the "new alt account" plus following that alt too that isn't even mine lol, don't try to lie.

**Comment by swagging-post** [comment]
Plus I just saw you unfollow yourself after I said that, you're not slick. Literally internet archived this all.

**Comment by Githubman6996** [comment]
I unfollowed them

**Comment by Githubman6996** [comment]
@swagging-post

**Comment by Githubman6996** [comment]
@swagging-post you gonna respond ???

**Comment by Githubman6996** [comment]
Hello ???

**Comment by swagging-post** [comment]
> I didn’t read your profile readme that says what your only real accounts are
> 
> blooketdevs isn’t me

wym blooket devs lol, ig u are impersonating me if you know your 1st user before changing it to my "alt"

**Comment by Githubman6996** [comment]
I'm not blooketdev bro

I literally was the one from this screenshot

**Comment by Githubman6996** [comment]
![IMG_9716](https://github.com/Githubman6996/Minesraft2-blooket-hack-website/assets/144396091/9cc7d7ad-bad1-4a67-9d51-8cb926df2def)
![IMG_9656](https://github.com/Githubman6996/Minesraft2-blooket-hack-website/assets/144396091/cfcbf9d8-bbd8-465a-a451-88f6341f439a)

**Comment by Githubman6996** [comment]
How do you plan for me to log in to a different account that fast it’s not me

**Comment by swagging-post** [comment]
There's an account switcher? Ik for a fact you can't play dumb like that

**Comment by Githubman6996** [comment]
Wdym an account switcher im a literal teenager

**Comment by Githubman6996** [comment]
You can't avoid the email blooket sent you

**Comment by Githubman6996** [comment]
![image](https://github.com/Githubman6996/Minesraft2-blooket-hack-website/assets/144396091/7a1217ec-baff-46d4-8a07-02e63d364bb1)

**Comment by Githubman6996** [comment]
@swagging-post

**Comment by Githubman6996** [comment]
You think lying gets you out of this

**Comment by swagging-post** [comment]
what, thats not true, the repo has been edited already so i'm fine lol.

**Comment by swagging-post** [comment]
oh yeah + GOODBYE IMPERSONATOR, NOW I DON'T HAVE TO WORRY ANYMORE LOL!

**Comment by Allenkimchi** [comment]
real
